version: '3.3'
services:
    db:
      image: mysql
      container_name: mysql_db
      environment:
        MYSQL_ROOT_PASSWORD: my_secret_password
      ports:
        - "3306:3306"
      security_opt:
        - seccomp:unconfined
      volumes:
        - ./docker-mysql-db:/var/lib/mysql